spring:
  profiles:
    active: dev

  messages:
    basename: i18n/messages

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.auth-url}/realms/${keycloak.realm}/protocol/openid-connect/certs # JSON Web Key URI to use to verify the JWT token.
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: ${keycloak.credentials.client-id}
            client-secret: ${keycloak.credentials.client-secret}
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            authorization-uri: ${keycloak.auth-url}/realms/${keycloak.realm}/protocol/openid-connect/auth
            token-uri: ${keycloak.auth-url}/realms/${keycloak.realm}/protocol/openid-connect/token

reactive:
  feign:
    httpclient:
      enabled: false
    hystrix:
      enabled: false
    loadbalancer:
      enabled: false
    circuit:
      breaker:
        enabled: flase
    client:
      config:
        default:
          connectTimeout: 100000
          readTimeout: 100000
    ribbon:
      enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

server:
  port: 8084

logging:
  level:
    com.japharr.keycloakadmin: Debug

keycloak:
  realm: ${KEYCLOAK_REALM:myrealm}
  auth-url: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:7070}/auth
  credentials:
    client-id: ${KEYCLOAK_CLIENT_ID:admin-connect}
    client-secret: ${KEYCLOAK_CLIENT_SECRET:b1b26004-a9d8-42f0-b7d2-69490aaea11f}
